name: 'nord-cloud-ghost'

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch and the specified folder
  push:
    branches:
      - main

jobs:
  lint-and-built:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker lint
        run: docker run --rm -i hadolint/hadolint < Dockerfile
        continue-on-error: true
        if: github.event_name == 'pull_request'

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: github.event_name != 'pull_request'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        if: github.event_name != 'pull_request'

      - name: Setup Short SHA
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
        if: github.event_name != 'pull_request'

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPOSITORY_NAME }}
          IMAGE_TAG: '${GITHUB_SHA::8}'
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA_SHORT .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA_SHORT
          docker tag  $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA_SHORT $ECR_REGISTRY/$ECR_REPOSITORY:dev 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev
        if: github.event_name != 'pull_request'
      
      - name: deploy ecs
        run: |
          docker run fabfuel/ecs-deploy:1.10.2 ecs deploy ${{ secrets.ECS_CLUSTER_NAME_DEV }} ${{ secrets.ECS_SERVICE_NAME_DEV }} --tag dev --region ${{ secrets.AWS_REGION }} --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: github.event_name != 'pull_request'



